name: ci
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        go-version:
          - 1.16.x
          - 1.15.x
          - 1.14.x
        os:
          - ubuntu

    name: build (${{ matrix.os }}/go-${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - run: go build .

  test:
    strategy:
      matrix:
        go-version:
          - 1.16.x
          - 1.15.x
          - 1.14.x
        os:
          - ubuntu

    name: test (${{ matrix.os }}/go-${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - run: go test -count=1 -race ./...

  qa:
    strategy:
      matrix:
        go-version:
          - 1.16.x
        os:
          - ubuntu

    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - run: go vet ./...
    - run: go install honnef.co/go/tools/cmd/staticcheck@v0.3.3
    - run: staticcheck ./...
